
// <copyright file="PreOperationarm_petCreate.cs" company="">
// Copyright (c) 2022 All Rights Reserved
// </copyright>
// <author></author>
// <date>7/12/2022 7:41:23 AM</date>
// <summary>Implements the PreOperationarm_petCreate Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>

using System;
using System.ServiceModel;
using Microsoft.Xrm.Sdk;

namespace PL400PowerPlatformSolution.PL400Plugins
{

    /// <summary>
    /// PreOperationarm_petCreate Plugin.
    /// </summary>    
    public class PreOperationarm_petCreate: PluginBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PreOperationarm_petCreate"/> class.
        /// </summary>
        /// <param name="unsecure">Contains public (unsecured) configuration information.</param>
        /// <param name="secure">Contains non-public (secured) configuration information.</param>
        public PreOperationarm_petCreate(string unsecure, string secure)
            : base(typeof(PreOperationarm_petCreate))
        {
            
           // TODO: Implement your custom configuration handling.
        }


        /// <summary>
        /// Main entry point for he business logic that the plug-in is to execute.
        /// </summary>
        /// <param name="localContext">The <see cref="LocalPluginContext"/> which contains the
        /// <see cref="IPluginExecutionContext"/>,
        /// <see cref="IOrganizationService"/>
        /// and <see cref="ITracingService"/>
        /// </param>
        /// <remarks>
        /// </remarks>
        protected override void ExecuteCdsPlugin(ILocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new InvalidPluginExecutionException(nameof(localContext));
            }           
            // Obtain the tracing service
            ITracingService tracingService = localContext.TracingService;

            try
            { 
                // Obtain the execution context from the service provider.  
                IPluginExecutionContext context = (IPluginExecutionContext)localContext.PluginExecutionContext;

                // Obtain the organization service reference for web service calls.  
                IOrganizationService currentUserService = localContext.CurrentUserService;

                // TODO: Implement your custom Plug-in business logic.
                // Check for the entity on which the plugin would be registered
                if (context.InputParameters.Contains("Target") && context.InputParameters["Target"] is Entity)
                {
                    var entity = (Entity)context.InputParameters["Target"];

                    // Check for entity name on which this plugin would be registered
                    if (entity.LogicalName == "arm_pet")
                    {
                        entity["arm_pettype"] = "Hello, plugin!";
                    }
                }

            }
            // Only throw an InvalidPluginExecutionException. Please Refer https://go.microsoft.com/fwlink/?linkid=2153829.
            catch (Exception ex)
            {
                tracingService?.Trace("An error occurred executing Plugin PL400PowerPlatformSolution.PL400Plugins.PreOperationarm_petCreate : {0}", ex.ToString());
                throw new InvalidPluginExecutionException("An error occurred executing Plugin PL400PowerPlatformSolution.PL400Plugins.PreOperationarm_petCreate .", ex);
            }	
        }
    }
}
