//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Microsoft Power Platform Tools")]
[assembly: AssemblyDescription("Microsoft Power Platform Tools for Visual Studio")]
[assembly: AssemblyCompany("Microsoft")]
[assembly: AssemblyProduct("Microsoft Dynamics© CRM")]
[assembly: AssemblyVersion("1.0.0.1")]
[assembly: AssemblyFileVersion("1.0.0.1")]
[assembly: AssemblyInformationalVersion("1.0.0.1+g580fe6c")]
[assembly: AssemblyCopyright("© 2021 Microsoft Corporation. All rights reserved")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyConfiguration("")]
[assembly: Guid("8d1914cd-c879-40d1-a2ac-756d720f71f5")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]

